# =============================================
# Centralized Log Aggregation Platform - Config
# =============================================

server.port=8080

# =============================================
# PostgreSQL Database
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/logplatform
spring.datasource.username=postgres
spring.datasource.password=20063891
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# JWT Configuration
# =============================================
jwt.secret=BugSlayers2026SuperSecretKeyMustBe256BitsLongForHS256Algorithm!!
jwt.expiration=86400000

# =============================================
# Logging
# =============================================
logging.level.com.logger=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=WARN